### ISSUE TITLE
Add response message to register API

### ISSUE THREAD

**Issue by pitoregia** [DigiLokal/DILO-FastAPI-Draft#7]
The current response is like this
``
[
  "Username already exist!"
]
``

And I had no idea how to take the response on Android and I don't think it possible, please change it to this for MY quality-of-life.
``
{
  "message": "Username already exist!"
}
``

Btw, I'm just trying the Issues features to look cool, don't mind me :p

**Comment by ardhanidzaky** [comment]
Fixed
